/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ActivationRouteImport } from './routes/activation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedEtablissementsRouteImport } from './routes/_authenticated/etablissements'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedHistoriqueRouteImport } from './routes/_authenticated/historique'
import { Route as AuthenticatedMonCompteRouteImport } from './routes/_authenticated/mon-compte'
import { Route as AuthenticatedPersonnelRouteImport } from './routes/_authenticated/personnel'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as InvitationTokenRouteImport } from './routes/invitation.$token'
import { Route as AuthenticatedClassesClassIdRouteImport } from './routes/_authenticated/classes.$classId'
import { Route as AuthenticatedElevesIndexRouteImport } from './routes/_authenticated/eleves.index'
import { Route as AuthenticatedElevesStudentIdRouteImport } from './routes/_authenticated/eleves.$studentId'
import { Route as AuthenticatedEnseignantsIndexRouteImport } from './routes/_authenticated/enseignants.index'
import { Route as AuthenticatedEnseignantsTeacherIdRouteImport } from './routes/_authenticated/enseignants.$teacherId'
import { Route as AuthenticatedEtablissementsIndexRouteImport } from './routes/_authenticated/etablissements.index'
import { Route as AuthenticatedEtablissementsIdRouteImport } from './routes/_authenticated/etablissements.$id'
import { Route as AuthenticatedPersonnelIndexRouteImport } from './routes/_authenticated/personnel.index'
import { Route as AuthenticatedPersonnelIdRouteImport } from './routes/_authenticated/personnel.$id'
import { Route as AuthenticatedElevesStudentIdIndexRouteImport } from './routes/_authenticated/eleves.$studentId.index'
import { Route as AuthenticatedElevesStudentIdScolariteRouteImport } from './routes/_authenticated/eleves.$studentId.scolarite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationRoute = ActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEtablissementsRoute =
  AuthenticatedEtablissementsRouteImport.update({
    id: '/etablissements',
    path: '/etablissements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoriqueRoute = AuthenticatedHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonCompteRoute = AuthenticatedMonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonnelRoute = AuthenticatedPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const InvitationTokenRoute = InvitationTokenRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClassesClassIdRoute =
  AuthenticatedClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedElevesIndexRoute =
  AuthenticatedElevesIndexRouteImport.update({
    id: '/eleves/',
    path: '/eleves/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedElevesStudentIdRoute =
  AuthenticatedElevesStudentIdRouteImport.update({
    id: '/eleves/$studentId',
    path: '/eleves/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnseignantsIndexRoute =
  AuthenticatedEnseignantsIndexRouteImport.update({
    id: '/enseignants/',
    path: '/enseignants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnseignantsTeacherIdRoute =
  AuthenticatedEnseignantsTeacherIdRouteImport.update({
    id: '/enseignants/$teacherId',
    path: '/enseignants/$teacherId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEtablissementsIndexRoute =
  AuthenticatedEtablissementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEtablissementsRoute,
  } as any)
const AuthenticatedEtablissementsIdRoute =
  AuthenticatedEtablissementsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedEtablissementsRoute,
  } as any)
const AuthenticatedPersonnelIndexRoute =
  AuthenticatedPersonnelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)
const AuthenticatedPersonnelIdRoute =
  AuthenticatedPersonnelIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPersonnelRoute,
  } as any)
const AuthenticatedElevesStudentIdIndexRoute =
  AuthenticatedElevesStudentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedElevesStudentIdRoute,
  } as any)
const AuthenticatedElevesStudentIdScolariteRoute =
  AuthenticatedElevesStudentIdScolariteRouteImport.update({
    id: '/scolarite',
    path: '/scolarite',
    getParentRoute: () => AuthenticatedElevesStudentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/auth': typeof AuthRoute
  '/etablissements': typeof AuthenticatedEtablissementsRouteWithChildren
  '/finance': typeof AuthenticatedFinanceRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/personnel': typeof AuthenticatedPersonnelRouteWithChildren
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/eleves/$studentId': typeof AuthenticatedElevesStudentIdRouteWithChildren
  '/enseignants/$teacherId': typeof AuthenticatedEnseignantsTeacherIdRoute
  '/etablissements/$id': typeof AuthenticatedEtablissementsIdRoute
  '/personnel/$id': typeof AuthenticatedPersonnelIdRoute
  '/eleves/': typeof AuthenticatedElevesIndexRoute
  '/enseignants/': typeof AuthenticatedEnseignantsIndexRoute
  '/etablissements/': typeof AuthenticatedEtablissementsIndexRoute
  '/personnel/': typeof AuthenticatedPersonnelIndexRoute
  '/eleves/$studentId/scolarite': typeof AuthenticatedElevesStudentIdScolariteRoute
  '/eleves/$studentId/': typeof AuthenticatedElevesStudentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/auth': typeof AuthRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/enseignants/$teacherId': typeof AuthenticatedEnseignantsTeacherIdRoute
  '/etablissements/$id': typeof AuthenticatedEtablissementsIdRoute
  '/personnel/$id': typeof AuthenticatedPersonnelIdRoute
  '/eleves': typeof AuthenticatedElevesIndexRoute
  '/enseignants': typeof AuthenticatedEnseignantsIndexRoute
  '/etablissements': typeof AuthenticatedEtablissementsIndexRoute
  '/personnel': typeof AuthenticatedPersonnelIndexRoute
  '/eleves/$studentId/scolarite': typeof AuthenticatedElevesStudentIdScolariteRoute
  '/eleves/$studentId': typeof AuthenticatedElevesStudentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/activation': typeof ActivationRoute
  '/auth': typeof AuthRoute
  '/_authenticated/etablissements': typeof AuthenticatedEtablissementsRouteWithChildren
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/historique': typeof AuthenticatedHistoriqueRoute
  '/_authenticated/mon-compte': typeof AuthenticatedMonCompteRoute
  '/_authenticated/personnel': typeof AuthenticatedPersonnelRouteWithChildren
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/_authenticated/classes/$classId': typeof AuthenticatedClassesClassIdRoute
  '/_authenticated/eleves/$studentId': typeof AuthenticatedElevesStudentIdRouteWithChildren
  '/_authenticated/enseignants/$teacherId': typeof AuthenticatedEnseignantsTeacherIdRoute
  '/_authenticated/etablissements/$id': typeof AuthenticatedEtablissementsIdRoute
  '/_authenticated/personnel/$id': typeof AuthenticatedPersonnelIdRoute
  '/_authenticated/eleves/': typeof AuthenticatedElevesIndexRoute
  '/_authenticated/enseignants/': typeof AuthenticatedEnseignantsIndexRoute
  '/_authenticated/etablissements/': typeof AuthenticatedEtablissementsIndexRoute
  '/_authenticated/personnel/': typeof AuthenticatedPersonnelIndexRoute
  '/_authenticated/eleves/$studentId/scolarite': typeof AuthenticatedElevesStudentIdScolariteRoute
  '/_authenticated/eleves/$studentId/': typeof AuthenticatedElevesStudentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activation'
    | '/auth'
    | '/etablissements'
    | '/finance'
    | '/historique'
    | '/mon-compte'
    | '/personnel'
    | '/tableau-de-bord'
    | '/invitation/$token'
    | '/classes/$classId'
    | '/eleves/$studentId'
    | '/enseignants/$teacherId'
    | '/etablissements/$id'
    | '/personnel/$id'
    | '/eleves/'
    | '/enseignants/'
    | '/etablissements/'
    | '/personnel/'
    | '/eleves/$studentId/scolarite'
    | '/eleves/$studentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activation'
    | '/auth'
    | '/finance'
    | '/historique'
    | '/mon-compte'
    | '/tableau-de-bord'
    | '/invitation/$token'
    | '/classes/$classId'
    | '/enseignants/$teacherId'
    | '/etablissements/$id'
    | '/personnel/$id'
    | '/eleves'
    | '/enseignants'
    | '/etablissements'
    | '/personnel'
    | '/eleves/$studentId/scolarite'
    | '/eleves/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/activation'
    | '/auth'
    | '/_authenticated/etablissements'
    | '/_authenticated/finance'
    | '/_authenticated/historique'
    | '/_authenticated/mon-compte'
    | '/_authenticated/personnel'
    | '/_authenticated/tableau-de-bord'
    | '/invitation/$token'
    | '/_authenticated/classes/$classId'
    | '/_authenticated/eleves/$studentId'
    | '/_authenticated/enseignants/$teacherId'
    | '/_authenticated/etablissements/$id'
    | '/_authenticated/personnel/$id'
    | '/_authenticated/eleves/'
    | '/_authenticated/enseignants/'
    | '/_authenticated/etablissements/'
    | '/_authenticated/personnel/'
    | '/_authenticated/eleves/$studentId/scolarite'
    | '/_authenticated/eleves/$studentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActivationRoute: typeof ActivationRoute
  AuthRoute: typeof AuthRoute
  InvitationTokenRoute: typeof InvitationTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation': {
      id: '/activation'
      path: '/activation'
      fullPath: '/activation'
      preLoaderRoute: typeof ActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/etablissements': {
      id: '/_authenticated/etablissements'
      path: '/etablissements'
      fullPath: '/etablissements'
      preLoaderRoute: typeof AuthenticatedEtablissementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historique': {
      id: '/_authenticated/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AuthenticatedHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-compte': {
      id: '/_authenticated/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof AuthenticatedMonCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personnel': {
      id: '/_authenticated/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof AuthenticatedPersonnelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invitation/$token': {
      id: '/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof InvitationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/classes/$classId': {
      id: '/_authenticated/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof AuthenticatedClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eleves/': {
      id: '/_authenticated/eleves/'
      path: '/eleves'
      fullPath: '/eleves/'
      preLoaderRoute: typeof AuthenticatedElevesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eleves/$studentId': {
      id: '/_authenticated/eleves/$studentId'
      path: '/eleves/$studentId'
      fullPath: '/eleves/$studentId'
      preLoaderRoute: typeof AuthenticatedElevesStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enseignants/': {
      id: '/_authenticated/enseignants/'
      path: '/enseignants'
      fullPath: '/enseignants/'
      preLoaderRoute: typeof AuthenticatedEnseignantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enseignants/$teacherId': {
      id: '/_authenticated/enseignants/$teacherId'
      path: '/enseignants/$teacherId'
      fullPath: '/enseignants/$teacherId'
      preLoaderRoute: typeof AuthenticatedEnseignantsTeacherIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etablissements/': {
      id: '/_authenticated/etablissements/'
      path: '/'
      fullPath: '/etablissements/'
      preLoaderRoute: typeof AuthenticatedEtablissementsIndexRouteImport
      parentRoute: typeof AuthenticatedEtablissementsRoute
    }
    '/_authenticated/etablissements/$id': {
      id: '/_authenticated/etablissements/$id'
      path: '/$id'
      fullPath: '/etablissements/$id'
      preLoaderRoute: typeof AuthenticatedEtablissementsIdRouteImport
      parentRoute: typeof AuthenticatedEtablissementsRoute
    }
    '/_authenticated/personnel/': {
      id: '/_authenticated/personnel/'
      path: '/'
      fullPath: '/personnel/'
      preLoaderRoute: typeof AuthenticatedPersonnelIndexRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
    '/_authenticated/personnel/$id': {
      id: '/_authenticated/personnel/$id'
      path: '/$id'
      fullPath: '/personnel/$id'
      preLoaderRoute: typeof AuthenticatedPersonnelIdRouteImport
      parentRoute: typeof AuthenticatedPersonnelRoute
    }
    '/_authenticated/eleves/$studentId/': {
      id: '/_authenticated/eleves/$studentId/'
      path: '/'
      fullPath: '/eleves/$studentId/'
      preLoaderRoute: typeof AuthenticatedElevesStudentIdIndexRouteImport
      parentRoute: typeof AuthenticatedElevesStudentIdRoute
    }
    '/_authenticated/eleves/$studentId/scolarite': {
      id: '/_authenticated/eleves/$studentId/scolarite'
      path: '/scolarite'
      fullPath: '/eleves/$studentId/scolarite'
      preLoaderRoute: typeof AuthenticatedElevesStudentIdScolariteRouteImport
      parentRoute: typeof AuthenticatedElevesStudentIdRoute
    }
  }
}

interface AuthenticatedEtablissementsRouteChildren {
  AuthenticatedEtablissementsIdRoute: typeof AuthenticatedEtablissementsIdRoute
  AuthenticatedEtablissementsIndexRoute: typeof AuthenticatedEtablissementsIndexRoute
}

const AuthenticatedEtablissementsRouteChildren: AuthenticatedEtablissementsRouteChildren =
  {
    AuthenticatedEtablissementsIdRoute: AuthenticatedEtablissementsIdRoute,
    AuthenticatedEtablissementsIndexRoute:
      AuthenticatedEtablissementsIndexRoute,
  }

const AuthenticatedEtablissementsRouteWithChildren =
  AuthenticatedEtablissementsRoute._addFileChildren(
    AuthenticatedEtablissementsRouteChildren,
  )

interface AuthenticatedPersonnelRouteChildren {
  AuthenticatedPersonnelIdRoute: typeof AuthenticatedPersonnelIdRoute
  AuthenticatedPersonnelIndexRoute: typeof AuthenticatedPersonnelIndexRoute
}

const AuthenticatedPersonnelRouteChildren: AuthenticatedPersonnelRouteChildren =
  {
    AuthenticatedPersonnelIdRoute: AuthenticatedPersonnelIdRoute,
    AuthenticatedPersonnelIndexRoute: AuthenticatedPersonnelIndexRoute,
  }

const AuthenticatedPersonnelRouteWithChildren =
  AuthenticatedPersonnelRoute._addFileChildren(
    AuthenticatedPersonnelRouteChildren,
  )

interface AuthenticatedElevesStudentIdRouteChildren {
  AuthenticatedElevesStudentIdScolariteRoute: typeof AuthenticatedElevesStudentIdScolariteRoute
  AuthenticatedElevesStudentIdIndexRoute: typeof AuthenticatedElevesStudentIdIndexRoute
}

const AuthenticatedElevesStudentIdRouteChildren: AuthenticatedElevesStudentIdRouteChildren =
  {
    AuthenticatedElevesStudentIdScolariteRoute:
      AuthenticatedElevesStudentIdScolariteRoute,
    AuthenticatedElevesStudentIdIndexRoute:
      AuthenticatedElevesStudentIdIndexRoute,
  }

const AuthenticatedElevesStudentIdRouteWithChildren =
  AuthenticatedElevesStudentIdRoute._addFileChildren(
    AuthenticatedElevesStudentIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEtablissementsRoute: typeof AuthenticatedEtablissementsRouteWithChildren
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHistoriqueRoute: typeof AuthenticatedHistoriqueRoute
  AuthenticatedMonCompteRoute: typeof AuthenticatedMonCompteRoute
  AuthenticatedPersonnelRoute: typeof AuthenticatedPersonnelRouteWithChildren
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedClassesClassIdRoute: typeof AuthenticatedClassesClassIdRoute
  AuthenticatedElevesStudentIdRoute: typeof AuthenticatedElevesStudentIdRouteWithChildren
  AuthenticatedEnseignantsTeacherIdRoute: typeof AuthenticatedEnseignantsTeacherIdRoute
  AuthenticatedElevesIndexRoute: typeof AuthenticatedElevesIndexRoute
  AuthenticatedEnseignantsIndexRoute: typeof AuthenticatedEnseignantsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEtablissementsRoute:
    AuthenticatedEtablissementsRouteWithChildren,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHistoriqueRoute: AuthenticatedHistoriqueRoute,
  AuthenticatedMonCompteRoute: AuthenticatedMonCompteRoute,
  AuthenticatedPersonnelRoute: AuthenticatedPersonnelRouteWithChildren,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedClassesClassIdRoute: AuthenticatedClassesClassIdRoute,
  AuthenticatedElevesStudentIdRoute:
    AuthenticatedElevesStudentIdRouteWithChildren,
  AuthenticatedEnseignantsTeacherIdRoute:
    AuthenticatedEnseignantsTeacherIdRoute,
  AuthenticatedElevesIndexRoute: AuthenticatedElevesIndexRoute,
  AuthenticatedEnseignantsIndexRoute: AuthenticatedEnseignantsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActivationRoute: ActivationRoute,
  AuthRoute: AuthRoute,
  InvitationTokenRoute: InvitationTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
