/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedEtablissementsRouteImport } from './routes/_authenticated/etablissements'
import { Route as AuthenticatedMonCompteRouteImport } from './routes/_authenticated/mon-compte'
import { Route as AuthenticatedPersonnelRouteImport } from './routes/_authenticated/personnel'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as InvitationTokenRouteImport } from './routes/invitation.$token'
import { Route as AuthenticatedEtablissementsIdRouteImport } from './routes/_authenticated/etablissements.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEtablissementsRoute =
  AuthenticatedEtablissementsRouteImport.update({
    id: '/etablissements',
    path: '/etablissements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonCompteRoute = AuthenticatedMonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonnelRoute = AuthenticatedPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const InvitationTokenRoute = InvitationTokenRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEtablissementsIdRoute =
  AuthenticatedEtablissementsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedEtablissementsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/etablissements': typeof AuthenticatedEtablissementsRouteWithChildren
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/personnel': typeof AuthenticatedPersonnelRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/etablissements/$id': typeof AuthenticatedEtablissementsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/etablissements': typeof AuthenticatedEtablissementsRouteWithChildren
  '/mon-compte': typeof AuthenticatedMonCompteRoute
  '/personnel': typeof AuthenticatedPersonnelRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/etablissements/$id': typeof AuthenticatedEtablissementsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/etablissements': typeof AuthenticatedEtablissementsRouteWithChildren
  '/_authenticated/mon-compte': typeof AuthenticatedMonCompteRoute
  '/_authenticated/personnel': typeof AuthenticatedPersonnelRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/_authenticated/etablissements/$id': typeof AuthenticatedEtablissementsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/etablissements'
    | '/mon-compte'
    | '/personnel'
    | '/tableau-de-bord'
    | '/invitation/$token'
    | '/etablissements/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/etablissements'
    | '/mon-compte'
    | '/personnel'
    | '/tableau-de-bord'
    | '/invitation/$token'
    | '/etablissements/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/etablissements'
    | '/_authenticated/mon-compte'
    | '/_authenticated/personnel'
    | '/_authenticated/tableau-de-bord'
    | '/invitation/$token'
    | '/_authenticated/etablissements/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InvitationTokenRoute: typeof InvitationTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/etablissements': {
      id: '/_authenticated/etablissements'
      path: '/etablissements'
      fullPath: '/etablissements'
      preLoaderRoute: typeof AuthenticatedEtablissementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-compte': {
      id: '/_authenticated/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof AuthenticatedMonCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personnel': {
      id: '/_authenticated/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof AuthenticatedPersonnelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invitation/$token': {
      id: '/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof InvitationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/etablissements/$id': {
      id: '/_authenticated/etablissements/$id'
      path: '/$id'
      fullPath: '/etablissements/$id'
      preLoaderRoute: typeof AuthenticatedEtablissementsIdRouteImport
      parentRoute: typeof AuthenticatedEtablissementsRoute
    }
  }
}

interface AuthenticatedEtablissementsRouteChildren {
  AuthenticatedEtablissementsIdRoute: typeof AuthenticatedEtablissementsIdRoute
}

const AuthenticatedEtablissementsRouteChildren: AuthenticatedEtablissementsRouteChildren =
  {
    AuthenticatedEtablissementsIdRoute: AuthenticatedEtablissementsIdRoute,
  }

const AuthenticatedEtablissementsRouteWithChildren =
  AuthenticatedEtablissementsRoute._addFileChildren(
    AuthenticatedEtablissementsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEtablissementsRoute: typeof AuthenticatedEtablissementsRouteWithChildren
  AuthenticatedMonCompteRoute: typeof AuthenticatedMonCompteRoute
  AuthenticatedPersonnelRoute: typeof AuthenticatedPersonnelRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEtablissementsRoute:
    AuthenticatedEtablissementsRouteWithChildren,
  AuthenticatedMonCompteRoute: AuthenticatedMonCompteRoute,
  AuthenticatedPersonnelRoute: AuthenticatedPersonnelRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InvitationTokenRoute: InvitationTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
